id: PF89CC589
initial_creation_type: ocr
source_metadata:
  volumes:
    f9374de691f24ba5a5cf63c771ef7f40:
      base_file: v083.txt
      image_group_id: I1PD95928
      title: ཚིགས་སུ་བཅད་པའི་དོན་བསྡུས་པ་ཞེས་བྱ་བའི་བསྟན་བཅོས།
      total_pages: 1296
      volume_number: 83
